name: marketplace_app
description: A complete  Flutter task with SQLite integration  for ITLegend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0  # For desktop platforms (Windows/Linux/macOS)
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # UI & Fonts
  google_fonts: ^6.1.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/